app:
    resource: '@AppBundle/Controller/'
    type: annotation


post_api:
    resource: "AppBundle\\Controller\\ApiController"
    type: rest
    prefix: /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
